//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int adminID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Contact_number { get; set; }
        public string email_address { get; set; }
        public string Address { get; set; }
    }
}
