//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int DeliveryID { get; set; }
        public int EmployeeID { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
