//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employeeID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string mobile_number { get; set; }
        public string Email_address { get; set; }
        public string Address { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int User_role { get; set; }
    }
}
