//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string Order_Number { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int PaymentID { get; set; }
        public Nullable<System.DateTime> Dateplaced { get; set; }
        public Nullable<System.DateTime> Dateprocessed { get; set; }
        public Nullable<System.DateTime> Datecompleted { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Order_Status Order_Status { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
