//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentID { get; set; }
        public string Payment_Method { get; set; }
        public string Payment_Amount { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public System.TimeSpan Payment_Time { get; set; }
    }
}
