//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Cart_Line = new HashSet<Cart_Line>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int ProductCategoryID { get; set; }
        public int ProductTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> InStock { get; set; }
        public string Image { get; set; }
        public Nullable<int> StockID { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_Line> Cart_Line { get; set; }
        public virtual Product_Category Product_Category { get; set; }
        public virtual Product_Type Product_Type { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
