//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order_Line
    {
        public int SupplierOrderLineID { get; set; }
        public int SupplierOrderID { get; set; }
        public int StockID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Stock Stock1 { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
