//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteOffLine
    {
        public int WriteOffLineID { get; set; }
        public int ProductID { get; set; }
        public int WriteOffSID { get; set; }
        public string Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual WriteOff WriteOff { get; set; }
    }
}
